apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-dev
  namespace: learning
  labels:
    moitruong: dev
    duan: k8s-learning-dev
spec:
  containers:
    - name: hello-pod
      image: 080196/hello-kube
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-staging
  namespace: learning
  labels:
    moitruong: staging
    duan: k8s-learning-staging
spec:
  containers:
    - name: hello-pod
      image: 080196/hello-kube
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-prod
  namespace: learning
  labels:
    moitruong: prod
    duan: k8s-learning-prod
spec:
  containers:
    - name: hello-pod
      image: 080196/hello-kube
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 3000
          protocol: TCP
